/* eslint-disable */

export const employees = [   
        {   
            id        : '7eb7c859-1347-4317-96b6-9476a7ec',
            employeeID       : '3111',     
            namee    : 'Bueno Trevor',
            harvestYear      : 2022,
            role       : ["Mechanic","Dispatcher"],
            email      : "BuenoTrevor@gmail.com",
            active     : true,
            fname:'Haris',
            lname:'Mahmood',
            city:'Kasur',
            address:'Johar Town',
            position:'Admin',
            salary:"10000",
            currentEmployee:'Yes',
        
        },
        {   
            id        : '7eb7c859-1347-4317-96b6-9476a7e2ba3c334343',
            employeeID       : '2425',     
            namee      : 'Roy Fitz',
            harvestYear      : 2022,
            role       : ["Crew Chief","Dispatcher"],
            email      : "royfitz@gmail.com",
            active     : true,
            fname:'Haris-1',
            lname:'Mahmood-2',
            city:'Kasur-2',
            address:'Johar Town-2',
            position:'Admin-2',
            salary:"20000",
            currentEmployee:'No',
        
        },
        {   
            id        : '7eb7c859-1347-4317-96b6-9476a7e2ba3c334343',
            employeeID       : '2425',     
            namee      : 'Roy Fitz',
            harvestYear      : 2022,
            role       : ["Crew Chief","Dispatcher"],
            email      : "royfitz@gmail.com",
            active     : true,
            fname:'Haris-1',
            lname:'Mahmood-2',
            city:'Kasur-2',
            address:'Johar Town-2',
            position:'Admin-2',
            salary:"20000",
            currentEmployee:'No',
        
        },
        {   
            id        : '7eb7c859-1347-4317-96b6-9476a7e2ba3c334343',
            employeeID       : '2425',     
            namee      : 'Roy Fitz',
            harvestYear      : 2022,
            role       : ["Crew Chief","Dispatcher"],
            email      : "royfitz@gmail.com",
            active     : true,
            fname:'Haris-1',
            lname:'Mahmood-2',
            city:'Kasur-2',
            address:'Johar Town-2',
            position:'Admin-2',
            salary:"20000",
            currentEmployee:'No',
        
        },
        {   
            id        : '7eb7c859-1347-4317-96b6-9476a7e2ba3c334343',
            employeeID       : '2425',     
            namee      : 'Roy Fitz',
            harvestYear      : 2022,
            role       : ["Crew Chief","Dispatcher"],
            email      : "royfitz@gmail.com",
            active     : true,
            fname:'Haris-1',
            lname:'Mahmood-2',
            city:'Kasur-2',
            address:'Johar Town-2',
            position:'Admin-2',
            salary:"20000",
            currentEmployee:'No',
        
        },
        {   
            id        : '7eb7c859-1347-4317-96b6-9476a7e2ba3c334343',
            employeeID       : '2425',     
            namee      : 'Roy Fitz',
            harvestYear      : 2022,
            role       : ["Crew Chief","Dispatcher"],
            email      : "royfitz@gmail.com",
            active     : true,
            fname:'Haris-1',
            lname:'Mahmood-2',
            city:'Kasur-2',
            address:'Johar Town-2',
            position:'Admin-2',
            salary:"20000",
            currentEmployee:'No',
        
        },
        {   
            id        : '7eb7c859-1347-4317-96b6-9476a7e2ba3c334343',
            employeeID       : '2425',     
            namee      : 'Roy Fitz',
            harvestYear      : 2022,
            role       : ["Crew Chief","Dispatcher"],
            email      : "royfitz@gmail.com",
            active     : true,
            fname:'Haris-1',
            lname:'Mahmood-2',
            city:'Kasur-2',
            address:'Johar Town-2',
            position:'Admin-2',
            salary:"20000",
            currentEmployee:'No',
        
        },
        {   
            id        : '7eb7c859-1347-4317-96b6-9476a7e2ba3c334343',
            employeeID       : '2425',     
            namee      : 'Roy Fitz',
            harvestYear      : 2022,
            role       : ["Crew Chief","Dispatcher"],
            email      : "royfitz@gmail.com",
            active     : true,
            fname:'Haris-1',
            lname:'Mahmood-2',
            city:'Kasur-2',
            address:'Johar Town-2',
            position:'Admin-2',
            salary:"20000",
            currentEmployee:'No',
        
        },
        {   
            id        : '7eb7c859-1347-4317-96b6-9476a7e2ba3c334343',
            employeeID       : '2425',     
            namee      : 'Roy Fitz',
            harvestYear      : 2022,
            role       : ["Crew Chief","Dispatcher"],
            email      : "royfitz@gmail.com",
            active     : true,
            fname:'Haris-1',
            lname:'Mahmood-2',
            city:'Kasur-2',
            address:'Johar Town-2',
            position:'Admin-2',
            salary:"20000",
            currentEmployee:'No',
        
        },
        {   
            id        : '7eb7c859-1347-4317-96b6-9476a7e2ba3c334343',
            employeeID       : '2425',     
            namee      : 'Roy Fitz',
            harvestYear      : 2022,
            role       : ["Crew Chief","Dispatcher"],
            email      : "royfitz@gmail.com",
            active     : true,
            fname:'Haris-1',
            lname:'Mahmood-2',
            city:'Kasur-2',
            address:'Johar Town-2',
            position:'Admin-2',
            salary:"20000",
            currentEmployee:'No',
        
        },
        {   
            id        : '7eb7c859-1347-4317-96b6-9476a7e2ba3c334343',
            employeeID       : '2425',     
            namee      : 'Roy Fitz',
            harvestYear      : 2022,
            role       : ["Crew Chief","Dispatcher"],
            email      : "royfitz@gmail.com",
            active     : true,
            fname:'Haris-1',
            lname:'Mahmood-2',
            city:'Kasur-2',
            address:'Johar Town-2',
            position:'Admin-2',
            salary:"20000",
            currentEmployee:'No',
        
        },
        {   
            id        : '7eb7c859-1347-4317-96b6-9476a7e2ba3c334343',
            employeeID       : '2425',     
            namee      : 'Roy Fitz',
            harvestYear      : 2022,
            role       : ["Crew Chief","Dispatcher"],
            email      : "royfitz@gmail.com",
            active     : true,
            fname:'Haris-1',
            lname:'Mahmood-2',
            city:'Kasur-2',
            address:'Johar Town-2',
            position:'Admin-2',
            salary:"20000",
            currentEmployee:'No',
        
        },
];
